include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Reasonable additional strictness for packages
    always_declare_return_types: true
    avoid_print: true
    prefer_single_quotes: true
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
